copyright = "© Nikko Kimbrough"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Los_Angeles"
timeout = "120s"
title = "Nikko Kimbrough"
[params]
  defaultTheme = "dark"
  description = "Professional Athlete, Photographer, Masseur, Coach"
  title = "Nikko Kimbrough"
  [params.author]
    email = "popfilmsmedia@gmail.com"
    name = "Nikko Kimbrough"
  [params.socialIcons]
    instagram = "https://www.instagram.com/p.o.p.films"
    #github = "https://github.com/ProgressionOverPerfectionFilms"
    youtube = "https://www.youtube.com/@ProgressionOverPerfectionFilms"
    email = "mailto:popfilmsmedia@gmail.com"
    website = "https://popfilms-pro.github.io/"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
    blue = "https://onlyfans.com/u402216658"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[services]
  [services.rss]
    limit = 100
